### ISSUE TITLE
Размещение кнопок

### ISSUE THREAD

**Issue by DinamickaDevelopment** [StepanNaryshkov/angular-project#1]
Кнопки хорошо помещяются в ряд, нет надобности делать их столбцом
![image](https://user-images.githubusercontent.com/12965606/27536099-5165f968-5a76-11e7-8c09-419cc3f1dd7b.png)

**Comment by StepanNaryshkov** [comment]
Поправил, но на мобильном оставил, так как не очень красиво смотрется
![screenshot 6](https://user-images.githubusercontent.com/12746043/27537023-904ac4a2-5a7a-11e7-87cd-b71ad17b83df.png)
