### ISSUE TITLE
отступ в форме

### ISSUE THREAD

**Issue by DinamickaDevelopment** [StepanNaryshkov/angular-project#2]
сильно больше растояние между первыми и последним полем формы
![image](https://user-images.githubusercontent.com/12965606/27538501-eece98cc-5a80-11e7-9b1e-34b11c45d243.png)

**Comment by StepanNaryshkov** [comment]
Данное расстояние как в макете, почти pixel perfect (+- 2px), или речь идет про НЕ декстоп?
