### ISSUE TITLE
Бургер-меню

### ISSUE THREAD

**Issue by DinamickaDevelopment** [StepanNaryshkov/angular-project#3]
Сделано хорошо, но есть недочеты, если меню открывается на весь мобильный екран, тогда долна пропадать возможность скролла, тогда у юзера , используя меню, не будет возможности случайно куда-то проскролить, можно сделать меню ровно по размеру дочерних елементов
![image](https://user-images.githubusercontent.com/12965606/27538672-ca872884-5a81-11e7-9b3f-48b67545c8f4.png)

**Comment by StepanNaryshkov** [comment]
Поправлю вечером
